import React from "react"
import Button from '../components/Button';
import Layout from '../components/Layout';
export default () =>

<Layout>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
  <h1> I'm in a layout!</h1>
</Layout>